// https://github.com/lvivduncan/levus-nav
{const e=document.querySelector("#levus-menu");if(null!=e){const s=document.createElement("div");s.className="levus-wrapper";const n=e.querySelectorAll("li");function changeMenu(){window.innerWidth<1200?(e.classList.remove("desktop"),e.classList.add("mobile")):(e.classList.remove("mobile"),e.classList.add("desktop"))}function showMenu(){e.classList.contains("show")?e.classList.remove("show"):e.classList.add("show")}function showUl(e){e.stopPropagation(),e.target.classList.contains("parent")&&this.classList.toggle("show")}n.forEach(e=>e.childNodes.length>1?e.className="parent":""),window.addEventListener("resize",changeMenu),document.addEventListener("DOMContentLoaded",changeMenu),document.addEventListener("DOMContentLoaded",n=>e.append(s)),s.addEventListener("click",showMenu),n.forEach(e=>{e.addEventListener("click",showUl)})}}

// https://github.com/lvivduncan/levus-onslide-slider
{const e=document.querySelector("#levus-slider");if(null!=e){const t=e.querySelectorAll("article"),s=t[0],d=e.querySelector("#levus-left"),o=e.querySelector("#levus-right");let i=0;const r=t.length-1;function hideArrow(){d.classList.add("hide"),o.classList.add("hide"),e.addEventListener("mouseover",()=>{d.removeAttribute("class"),o.removeAttribute("class")}),e.addEventListener("mouseout",()=>{d.classList.add("hide"),o.classList.add("hide")})}function autoScroll(){setInterval(()=>{t.forEach(e=>e.removeAttribute("class")),i<r?i++:i=0,t[i].classList.add("show")},8e3)}d.addEventListener("click",()=>{setTimeout(()=>{t.forEach(e=>e.removeAttribute("class")),i<r?i++:i=0,t[i].classList.add("show")},500)}),o.addEventListener("click",()=>{setTimeout(()=>{t.forEach(e=>e.removeAttribute("class")),0===i?i=r:i--,t[i].classList.add("show")},500)}),document.addEventListener("DOMContentLoaded",()=>window.innerWidth<1200?autoScroll():hideArrow()),document.addEventListener("DOMContentLoaded",()=>s.classList.add("show")),window.addEventListener("resize",()=>window.innerWidth<1200?autoScroll():hideArrow())}}

// https://github.com/lvivduncan/levus-table
const table=document.querySelectorAll("table");table.length>0&&table.forEach(e=>{const t=document.createElement("div");t.className="levus-table-wrapper";const l=e.cloneNode(!0);e.replaceWith(t),t.append(l)});

// https://github.com/lvivduncan/levus-modal
function levusModal(e,t){const s=document.querySelector(e),c=document.querySelector(t),d=document.createElement("div");d.classList.add("levus-close"),document.body.append(d),s.addEventListener("click",e=>{c.classList.add("active"),document.body.classList.add("levus-body"),d.classList.add("active")}),d.addEventListener("click",e=>{c.classList.remove("active"),document.body.removeAttribute("class"),d.classList.remove("active")}),document.addEventListener("keyup",e=>{"Escape"!==e.key&&"Escape"!==e.keyCode||(c.classList.remove("active"),document.body.removeAttribute("class"),d.classList.remove("active"))})}

// https://github.com/lvivduncan/levus-parallax
{const e=document.querySelector(".levus-parallax");if(null!=e){const t=e.offsetTop,l=document.querySelectorAll(".levus-parallax article");window.addEventListener("scroll",()=>{const e=document.documentElement.clientHeight,o=window.pageYOffset;l.forEach(l=>{e+o>t?l.style.backgroundPositionY=`-${(e+o-t)/3}px`:l.removeAttribute("style")})})}}